// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA2XlD1Tm3wJfwAtF7KqTGwobX5Ywalyic',
//     appId: '1:1084756615117:web:3634c227ead9ec89b02e84',
//     messagingSenderId: '1084756615117',
//     projectId: 'bumble-14907',
//     authDomain: 'bumble-14907.firebaseapp.com',
//     storageBucket: 'bumble-14907.appspot.com',
//     measurementId: 'G-QZ15WNH0W2',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBS_cxiTC6yKJ4T2y86eX_9bihfDkQRqZE',
//     appId: '1:1084756615117:android:85aa9d297944f69fb02e84',
//     messagingSenderId: '1084756615117',
//     projectId: 'bumble-14907',
//     storageBucket: 'bumble-14907.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBTPrIcjBmWbM4nJA739yVxgXI01O4kyGY',
//     appId: '1:1084756615117:ios:e5955e13b14f94dfb02e84',
//     messagingSenderId: '1084756615117',
//     projectId: 'bumble-14907',
//     storageBucket: 'bumble-14907.appspot.com',
//     iosClientId: '1084756615117-r72higqqsup491ja5mm6anu8em0iv6fa.apps.googleusercontent.com',
//     iosBundleId: 'com.example.bumbleBot',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBTPrIcjBmWbM4nJA739yVxgXI01O4kyGY',
//     appId: '1:1084756615117:ios:e5955e13b14f94dfb02e84',
//     messagingSenderId: '1084756615117',
//     projectId: 'bumble-14907',
//     storageBucket: 'bumble-14907.appspot.com',
//     iosClientId: '1084756615117-r72higqqsup491ja5mm6anu8em0iv6fa.apps.googleusercontent.com',
//     iosBundleId: 'com.example.bumbleBot',
//   );
// }
